### ISSUE TITLE
Adding two images not working

### ISSUE THREAD

**Issue by andresteves** [pgorzelany/ScratchCardView#6]
Hi,

I am trying to use 2 images as a cover and container. But the cover and container images show as the same. When scratching nothing is actually seen.

I am using Xcode 9.4.2

**Comment by pgorzelany-sofomo** [comment]
Can you share some code so its easier to replicate?

**Comment by pgorzelany** [comment]
Can you share some of your code so its easier to debug?

**Comment by andresteves** [comment]
Sorry about this but it was a mistake on my side.
