### ISSUE TITLE
'layer <CALayer: 0x600001d90660> is a part of cycle in its layer tree' *** First throw call stack

### ISSUE THREAD

**Issue by nikmun** [pgorzelany/ScratchCardView#8]
Hi,

I am getting this error each time. I have created two UIViews one on another. First view (content view) has label in it and second view (the view on which we need to scratch) has image and a label in it.

Am I doing something wrong? Or there is some issue with the code? Please help

**Comment by pgorzelany** [comment]
Probably an issue with your code. Read here:
https://stackoverflow.com/questions/31553111/layer-is-a-part-of-cycle-in-its-layer-tree-ios-9-swift-2
